### ISSUE TITLE
希望作者大大能出有控制台的版本

### ISSUE THREAD

**Issue by Nothend** [sleikang/media_server_tools#53]
非常感谢作者大大得代码，解决了emby中文得问题，真心不错。就是有时候信息更新了，要重新跑一遍，能否出一个控制台，可以罗列媒体文件，手动单个进行补充更新，感谢！好人一生平安～

**Comment by sleikang** [comment]
软件会定时自动刷新 没必要手动运行，每添加一个媒体就去手动执行一次那自动化就没意义了 等于手动修改多麻烦
