### ISSUE TITLE
运行，日志报错基本都是：获取TMDB人物**信息失败, 异常错误，Max retries exceeded with url:Connection to api.themoviedb.org timed out.

### ISSUE THREAD

**Issue by chong206** [sleikang/media_server_tools#70]
- 2023-09-13 08:25:32,300 INFO: 获取TMDB人物[Patrick Jordan]ID[1244314]信息失败, 异常错误：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/person/1244314?api_key=******&language=zh-TW (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6e95170070>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
- 2023-09-13 08:25:32,172 INFO: 获取TMDB人物[Shirin Caiola]ID[1185594]信息失败, 异常错误：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/person/1185594?api_key=******&language=zh-SG (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6e95173250>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
- 2023-09-13 08:25:31,532 INFO: 获取TMDB人物[Don Sinnar]ID[2691583]信息失败, 异常错误：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/person/2691583?api_key=******&language=zh-TW (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6e94434910>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
- 2023-09-13 08:24:11,276 INFO: 获取TMDB人物[Dan Amboyer]ID[1190987]信息失败, 异常错误：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/person/1190987?api_key=******&language=zh-SG (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6e94434b80>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
- 2023-09-13 08:24:09,996 INFO: 获取TMDB人物[Marshall Dancing Elk Lucas]ID[3865549]信息失败, 异常错误：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/person/3865549?api_key=******&language=zh-CN (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6e94435db0>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
- 2023-09-13 08:23:25,068 INFO: 获取TMDB人物[Patrick Jordan]ID[1244314]信息失败, 异常错误：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/person/1244314?api_key=******&language=zh-SG (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6e94437340>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))

emby中TMDB能正常刮削

**Comment by hyapollo** [comment]
没科学上网。Connection to api.themoviedb.org timed out已经说的很明显

**Comment by qhly2010** [comment]
我这里api.tmdb.org是通的，把api.themovie.org替换了就成功运行了

**Comment by chong206** [comment]
> 我这里api.tmdb.org是通的，把api.themovie.org替换了就成功运行了

非常感谢谢，修改后可以正常运行获取成功了，我这api.themovie.org也是通的能为什么刮不到，奇怪。
