### ISSUE TITLE
请问下，我刮削到一半梯子断了，导致一部分演员名是中文一部分是英文

### ISSUE THREAD

**Issue by 7-orion** [sleikang/media_server_tools#73]
我把整个程序删除重新配置后，重新刮削显示的都是xxx处理完成，实际并没有替换，请问该如何操作？谢谢

**Comment by 7-orion** [comment]
不是因为该影片的演员没有中文译名 豆瓣查看过

**Comment by sleikang** [comment]
你可以让媒体服务器强制刷新下元数据 比如如果用EMBY 他会把所有数据覆盖掉
