### ISSUE TITLE
程序刮削自动停止，日志也没报错

### ISSUE THREAD

**Issue by Llllwood** [sleikang/media_server_tools#78]
如题，版本是最新的2.3.0
安装平台为群辉7.1 docker：
![mst](https://github.com/sleikang/MediaServerTools/assets/144126126/c599fd56-f3b9-4bc8-9d68-67375314cc0a)
配置文件：
![mst-config](https://github.com/sleikang/MediaServerTools/assets/144126126/a737c9d5-7bf5-4d4c-855b-69c89796e084)
日志：
[log.txt](https://github.com/sleikang/MediaServerTools/files/12865209/log.txt)

**Comment by Llllwood** [comment]
![photo_2023-10-11_13-34-04](https://github.com/sleikang/MediaServerTools/assets/144126126/344536b6-da0c-4b21-b597-d4b5583420bf)
启动没多久就自动停止了

**Comment by sleikang** [comment]
尝试下新版试试
