### ISSUE TITLE
请问下这个是什么问题？

### ISSUE THREAD

**Issue by karasfjm** [sleikang/media_server_tools#81]
机器是黑群
![错误](https://github.com/sleikang/MediaServerTools/assets/127328702/5a12f1e0-54d1-4530-ae9e-342cac42a892)

**Comment by sleikang** [comment]
就是你刮削的原始数据没保存TMDB和TMDB的ID
![image](https://github.com/sleikang/MediaServerTools/assets/23020770/11c98f51-b912-4329-9200-c28eee824622)
