### ISSUE TITLE
无法识别英文名称，演员信息全部显示人物不存在

### ISSUE THREAD

**Issue by morisama11** [sleikang/media_server_tools#84]
![PixPin_2023-12-24_02-43-07](https://github.com/sleikang/MediaServerTools/assets/101331616/87c3107a-01ec-4536-9848-aa70c4495b25)

如图，我使用的是tinyMediaManager刮削整理好再让emby读取的方式，但tmm的演员信息都是英文，貌似插件不起作用

**Comment by sleikang** [comment]
是因为你刮削的数据没有存人物本身的TMDB和IMDB对应人物的ID，只有人物名称是没用的
