### ISSUE TITLE
Emby演员名能转换成中文，但是演员头像还是没有刮削出来

### ISSUE THREAD

**Issue by venom6y** [sleikang/media_server_tools#89]
![2024-03-13_221128](https://github.com/sleikang/MediaServerTools/assets/36263387/a620c196-f209-4906-a1f3-1196ed2670fa)
![2024-03-13_221156](https://github.com/sleikang/MediaServerTools/assets/36263387/e37255e0-f27d-4808-9df0-106a03788013)
有谁知道是什么原因吗？

**Comment by sleikang** [comment]
这个是因为你自己用了Nastool或者MoviePilot等其他导入nfo刮削数据造成的emby不会拉取人物头像，你要用emby自己的刮削，这个和软件没有关系，软件只是在已经刮削好的数据更新名称 不会改变原始刮削的其他数据
