### ISSUE TITLE
演员名字部分中文部分还是英文

### ISSUE THREAD

**Issue by king1393** [sleikang/media_server_tools#90]
使用win和群晖docker执行都存在同样情况，看日志显示媒体已经处理完成了，但是emby的演员名字并不是全部中文，部分还是英文，查看豆瓣是有中文名的并不是英文名，这是怎么回事？
![QQ截图20240401150033](https://github.com/sleikang/MediaServerTools/assets/32534889/365d7b67-0630-4491-a935-8ae58d357809)

**Comment by sleikang** [comment]
软件是拿人物的这2个id去豆瓣对比是不是同一个人物
![image](https://github.com/sleikang/MediaServerTools/assets/23020770/6b508499-bd11-482b-87be-521745ed7bfe)
