### ISSUE TITLE
若豆瓣的信息里的角色名为演员的，都会更改成演员，请问如何让它在豆瓣角色名为演员的时候，不进行替换？如图示

### ISSUE THREAD

**Issue by longerpt** [sleikang/media_server_tools#95]
![Snipaste_2024-04-30_20-46-20](https://github.com/sleikang/media_server_tools/assets/134587862/d3c3a6c9-5a9e-49a7-a42c-8c64b539a815)
![Snipaste_2024-04-30_20-47-39](https://github.com/sleikang/media_server_tools/assets/134587862/fac7804b-8203-4eaf-aa90-e82ac98f843a)
![Snipaste_2024-04-30_20-48-12](https://github.com/sleikang/media_server_tools/assets/134587862/3199033b-2ec9-4515-ad99-c83fe23c2784)

**Comment by sleikang** [comment]
已经增加该验证
