### ISSUE TITLE
排除媒体文件夹时，能否增加排除媒体库文件夹中的某个剧？

### ISSUE THREAD

**Issue by chong206** [sleikang/media_server_tools#97]
排除媒体文件夹时，排除的是整个媒体库文件夹中的内容。
能否增加排除媒体库文件夹中的某个剧？

**Comment by sleikang** [comment]
已经增加功能
![image](https://github.com/sleikang/media_server_tools/assets/23020770/b86aef44-57e3-495a-afa5-fc3eb6652017)
