### ISSUE TITLE
请问剧集组该如何配置

### ISSUE THREAD

**Issue by ChangJun1** [sleikang/media_server_tools#98]
如题，tmdb剧集组配置除了填入对应id之外，文件结构应该是什么样。比如说有些番剧官方是两季，但是集号（章节编号）是连续的，这种情况tmdb大多数情况下都只归到一季。如果我要使用剧集组的话，应该怎么建立目录结构呢？假如说有一个番是两季共24集，第一季是12话，第二季也是第1到12话，但是集号是13到24，那我命名应该是Season 1\S01E01-S01E24这样，还是Season 1\S01E01-S01E12和Season 2\S02E01-S02E12，还是有什么其他的命名规则呢？

**Comment by sleikang** [comment]
剧集组有几季你自己就配置几季 这个肯定是一一对应的
