### ISSUE TITLE
一直报搜索太频繁.

### ISSUE THREAD

**Issue by ati121** [sleikang/media_server_tools#99]
好像就成功了几个.就开始报频繁了..请问这种该如何解决
![12](https://github.com/sleikang/media_server_tools/assets/72114654/34da3c91-4284-4ec2-a747-385e7f8e45cf)

**Comment by rockhia** [comment]
#线程数量 豆瓣API有请求频率限制建议线程数量不要过多
    threadnum: 1
将线程修改为1，存在同样的问题
![image](https://github.com/sleikang/media_server_tools/assets/90016652/8ee48864-8cc4-4ec0-b502-2e4a59db0dde)

**Comment by rockhia** [comment]
仅开启豆瓣评分更新，其他关闭。1349仍然出错，同时emby内的评分并没有更新
![image](https://github.com/sleikang/media_server_tools/assets/90016652/bc7a777d-ff18-43f5-bc80-64c6fe088190)

![image](https://github.com/sleikang/media_server_tools/assets/90016652/83135a28-79d3-4345-bb59-9dd1ee92859d)

**Comment by sleikang** [comment]
可以开启一个线程，豆瓣 api 延迟改成 30 秒以上，这个是豆瓣限制没办法
